"""removed notes column from orders table

Revision ID: fdc6d2eaff10
Revises: d7a5a27646b7
Create Date: 2026-03-16 23:52:16.246726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc6d2eaff10'
down_revision = 'd7a5a27646b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
